#!/bin/bash
# copy this file to build.sh
# sh build.sh
# composer create-project laravel/laravel example-app

curl -s "https://laravel.build/example-app?with=mysql,redis" | bash
mv example-app/* ./
mv example-app/.* ./
rm -rf example-app

./vendor/bin/sail up
